# Generated by Django 4.1.1 on 2022-09-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpage',
            old_name='intro',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='to_address',
        ),
    ]
