# Generated by Django 4.1.1 on 2022-09-27 07:19

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_intro_formpage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
